env:
  - CODECLIMATE_REPO_TOKEN=7004fde364557acfcfbdec3cd2220e0bd9ccc9936b10ad852657954cbb5c3579 ELASTICSEARCH_URL=http://localhost:9200
language: ruby
rvm:
  - 2.1.2
before_install:
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.3.0
  - sudo service elasticsearch start
