elasticsearch_url: http://localhost:9200
storage: ElasticStorage
password: password
api_key: api_key

test:
  elasticsearch_url: http://localhost:9201
  storage: MemoryStorage

production:
  elasticsearch_url: <%= ENV['BONSAI_URL']%>
